export const categoryList = [
  "Computer Science & Engineering",
  "Programming & Software Development",
  "Computer Systems & Architecture",
  "Data & Information",
  "Artificial Intelligence & Machine Learning",
  "Graphics & Media",
  "Computational Thinking & Problem-Solving",
  "Digital Literacy & Cybersecurity",
  "Web Technologies & Internet",
  "Electronics & Robotics",
  "Mathematics for Computing",
  "Game Development",
  "Mobile App Development",
  "Software Engineering",
  "Cloud Computing",
  "Human-Computer Interaction (HCI)",
  "Operating Systems & Virtualisation",
  "Network & Internet Security",
  "Database Management Systems",
  "Cyber-Physical Systems & IoT",
  "Ethical Hacking & Penetration Testing",
];
